CREATE DATABASE SPMEDICALGROUP
USE SPMEDICALGROUP

CREATE TABLE TIPO_USUARIO(
ID INT IDENTITY PRIMARY KEY
, NOME VARCHAR(100) UNIQUE  NOT NULL 
);



CREATE TABLE USUARIO(
ID INT IDENTITY PRIMARY KEY 
,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID)
,EMAIL VARCHAR(80) UNIQUE NOT NULL
,SENHA VARCHAR(50) NOT NULL 
);

CREATE TABLE CLINICA(
ID INT IDENTITY PRIMARY KEY 
,RAZAO_SOCIAL VARCHAR(100)  UNIQUE NOT NULL
,NOME_FANTASIA VARCHAR(150) UNIQUE NOT NULL
,ENDERECO VARCHAR(200) NOT NULL
,CNPJ VARCHAR(20) NOT NULL
,TELEFONE VARCHAR(11) UNIQUE NOT NULL);

CREATE TABLE ESPECIALIDADE(
ID INT  IDENTITY PRIMARY KEY 
, NOME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE STATUS (
ID INT IDENTITY PRIMARY KEY
,SITUACAO VARCHAR(50)NOT NULL UNIQUE );

CREATE TABLE MEDICO (
ID INT IDENTITY PRIMARY KEY 
,CRM VARCHAR (10) NOT NULL UNIQUE 
,NOME VARCHAR(100) NOT NULL UNIQUE 
, ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADE(ID)
,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA (ID)  );

--Altera a tabela do medico,
--Inclui uma chave estrangeira para tabela medico
ALTER TABLE MEDICO
ADD ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID)

CREATE TABLE PRONTUARIO(
ID INT IDENTITY PRIMARY KEY 
,NOME VARCHAR(150) NOT NULL
,CPF INT NOT NULL UNIQUE
, RG INT NOT NULL UNIQUE
, ENDERECO VARCHAR(100) NOT NULL 
);
ALTER TABLE PRONTUARIO
ADD ID_USUARIO INT FOREIGN KEY REFERENCES USUARIO(ID)

CREATE TABLE CONSULTAS(
ID INT IDENTITY PRIMARY KEY,
ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIO(ID)
,ID_MEDICO INT FOREIGN KEY REFERENCES MEDICO (ID)
,DATA DATETIME NOT NULL
, ID_STATUS INT FOREIGN KEY REFERENCES STATUS(ID)
,DESCRICAO VARCHAR(250) NOT NULL);